import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { DEFAULT_PROMPT_TEMPLATE, renderPrompt } from '../lib/promptTemplate';
import {
  VocabValidationError,
  importVocab,
  loadVocab,
  mergeVocab,
  saveVocab,
} from '../lib/vocab';

const PREFS_KEY = 'vocab-import-prefs';

type Prefs = { sourceLang: string; targetLang: string };

function loadPrefs(): Prefs {
  try {
    const raw = localStorage.getItem(PREFS_KEY);
    if (!raw) return { sourceLang: '', targetLang: '' };
    const p = JSON.parse(raw) as Partial<Prefs>;
    return {
      sourceLang: typeof p.sourceLang === 'string' ? p.sourceLang : '',
      targetLang: typeof p.targetLang === 'string' ? p.targetLang : '',
    };
  } catch {
    return { sourceLang: '', targetLang: '' };
  }
}

function savePrefs(p: Prefs): void {
  localStorage.setItem(PREFS_KEY, JSON.stringify(p));
}

export default function Import() {
  const navigate = useNavigate();
  const [prefs, setPrefs] = useState<Prefs>(loadPrefs);
  const [template, setTemplate] = useState(DEFAULT_PROMPT_TEMPLATE);
  const [editing, setEditing] = useState(false);
  const [pasted, setPasted] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [copyState, setCopyState] = useState<'idle' | 'copied' | 'failed'>('idle');

  useEffect(() => {
    savePrefs(prefs);
  }, [prefs]);

  const existing = loadVocab(localStorage);
  const prompt = renderPrompt(prefs.sourceLang, prefs.targetLang, template);

  const onCopy = async () => {
    try {
      await navigator.clipboard.writeText(prompt);
      setCopyState('copied');
    } catch {
      setCopyState('failed');
    }
    setTimeout(() => setCopyState('idle'), 1500);
  };

  const onImport = () => {
    setError(null);
    try {
      const incoming = importVocab(pasted);
      if (incoming.words.length === 0) {
        setError('The pasted JSON contains no words.');
        return;
      }
      const merged = mergeVocab(existing, incoming);
      saveVocab(localStorage, merged);
      navigate('/');
    } catch (e) {
      if (e instanceof VocabValidationError) setError(e.message);
      else setError(`Unexpected error: ${(e as Error).message}`);
    }
  };

  return (
    <main className="min-h-dvh p-6 bg-sky-50 text-slate-900">
      <div className="max-w-2xl mx-auto space-y-6">
        <header>
          <h1 className="text-3xl font-bold">Import vocabulary</h1>
          <p className="text-slate-600 mt-1">
            Vocab is generated by an external AI from any source you have (textbook page, word list,
            lesson notes). Set your languages, copy the prompt, paste it into ChatGPT / Claude /
            Gemini together with your source material, then paste the JSON response back here.
          </p>
        </header>

        <section className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <label className="block">
            <span className="text-sm font-medium">Source language (the words to learn)</span>
            <input
              type="text"
              value={prefs.sourceLang}
              onChange={(e) => setPrefs((p) => ({ ...p, sourceLang: e.target.value }))}
              placeholder="e.g. German"
              className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 bg-white"
            />
          </label>
          <label className="block">
            <span className="text-sm font-medium">Target language (your known language)</span>
            <input
              type="text"
              value={prefs.targetLang}
              onChange={(e) => setPrefs((p) => ({ ...p, targetLang: e.target.value }))}
              placeholder="e.g. Czech"
              className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 bg-white"
            />
          </label>
        </section>

        <section>
          <div className="flex items-center justify-between mb-2">
            <h2 className="text-lg font-semibold">1. Copy the prompt</h2>
            <div className="space-x-3 text-sm">
              <button
                type="button"
                onClick={() => setEditing((e) => !e)}
                className="underline text-sky-700"
              >
                {editing ? 'Done editing' : 'Edit'}
              </button>
              {editing && (
                <button
                  type="button"
                  onClick={() => setTemplate(DEFAULT_PROMPT_TEMPLATE)}
                  className="underline text-sky-700"
                >
                  Reset to default
                </button>
              )}
            </div>
          </div>
          {editing ? (
            <textarea
              value={template}
              onChange={(e) => setTemplate(e.target.value)}
              rows={18}
              className="w-full font-mono text-xs rounded-lg border border-slate-300 p-3 bg-white"
              spellCheck={false}
            />
          ) : (
            <pre className="w-full max-h-96 overflow-auto font-mono text-xs rounded-lg border border-slate-300 p-3 bg-white whitespace-pre-wrap">
              {prompt}
            </pre>
          )}
          <button
            type="button"
            onClick={onCopy}
            className="mt-3 inline-flex items-center px-4 py-2 rounded-lg bg-sky-600 text-white font-medium active:scale-95 transition min-h-11"
          >
            {copyState === 'copied' && 'Copied!'}
            {copyState === 'failed' && 'Copy failed — select and copy manually'}
            {copyState === 'idle' && 'Copy prompt'}
          </button>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">2. Paste the AI&rsquo;s JSON response</h2>
          <textarea
            value={pasted}
            onChange={(e) => setPasted(e.target.value)}
            rows={10}
            placeholder='{"settings":{"articlePrefixes":[]},"words":[...]}'
            className="w-full font-mono text-xs rounded-lg border border-slate-300 p-3 bg-white"
            spellCheck={false}
          />
          {error && (
            <p className="mt-2 text-sm text-rose-700 bg-rose-50 border border-rose-200 rounded p-2">
              {error}
            </p>
          )}
          <button
            type="button"
            onClick={onImport}
            disabled={!pasted.trim()}
            className="mt-3 inline-flex items-center px-4 py-2 rounded-lg bg-emerald-600 text-white font-medium active:scale-95 transition disabled:opacity-50 disabled:cursor-not-allowed min-h-11"
          >
            Import
          </button>
        </section>

        <footer className="text-sm text-slate-600 border-t border-slate-200 pt-4 flex items-center justify-between gap-4">
          <span>
            {existing.words.length === 0
              ? 'No vocab loaded yet.'
              : `Currently loaded: ${existing.words.length} words. Importing merges by id; progress is preserved.`}
          </span>
          {existing.words.length > 0 && (
            <Link to="/" className="underline text-sky-700 shrink-0">
              Back home
            </Link>
          )}
        </footer>
      </div>
    </main>
  );
}
